swagger: "2.0"
info:
  description: "vtuber test API schema"
  version: "1.0.0"
  title: "vtuber test"
  contact:
    email: "contact@virtio.com.cn"
  license:
    name: "AGPL-3.0-or-later"
    url: "https://www.gnu.org/licenses/agpl-3.0.html"
basePath: "/api"
tags:
  - name: user
  - name: question
schemes:
  - "https"
  - "http"
paths:
  /user:
    post:
      tags:
        - user
      description: create a new user
      responses:
        200:
          description: success
  /user/self:
    get:
      tags:
        - user
      description: get self information
      responses:
        200:
          description: success
  /user/{username}/session:
    post:
      tags:
        - user
      description: login (create new session)
      responses:
        200:
          description: success
  /user/self/bilbili/verify_code:
    post:
      tags:
        - user
      description: create new bilbili challenge code
      responses:
        200:
          description: success
  /user/by-id/{id}/follow:
    post:
      tags:
        - user
      description: follow other user
      responses:
        200:
          description: success
    delete:
      tags:
        - user
      description: unfollow other user
      responses:
        200:
          description: success
  /question:
    post:
      tags:
        - question
      description: create new question
      responses:
        200:
          description: success
  /question/{qid}:
    get:
      tags:
        - question
      description: get a question by id
      responses:
        200:
          description: success
    delete:
      tags:
        - question
      description: delete a question by id
      responses:
        200:
          description: success